### ISSUE TITLE
Foreign key relationships and table and class naming

### ISSUE THREAD

**Issue by DrSkippy** [jeffknupp/sandman#12]
A tables with foreign key relationship to a second table causes a crash (KeyError) if class name != table name. Work around is to name class exactly the same as the table.

E.g. my program cadmini.py has 

```
class Edcs(Model):
    __tablename__ = 'edcs'
```

for error

Traceback (most recent call last):
  File "./cadmini.py", line 74, in <module>
    activate_admin_classes()
  File "/usr/local/lib/python2.7/dist-packages/sandman/model/**init**.py", line 59, in activate_admin_classes
    _prepare_relationships()
  File "/usr/local/lib/python2.7/dist-packages/sandman/model/__init__.py", line 50, in _prepare_relationships
    other = current_app.classes_by_name[foreign_key['referred_table']]
KeyError: u'edcs'

**Comment by jeffknupp** [comment]
Finally got around to squashing this. Should work fine now.
