### ISSUE TITLE
foreign key causing weird behavior

### ISSUE THREAD

**Issue by darengit** [jeffknupp/sandman#14]
Using mysql connector python to connect to mysql we have a table (job_schedule) with the following foreign key constraint:

CONSTRAINT `js_fk_data_source` FOREIGN KEY (`data_source`) REFERENCES `data_sources` (`name`)

note that job_schedule.data_source is constrained to data_sources.name, but job_schedule.name does not exist. In this case when we attempt to access /job_schedules using sandman we get this error:

Traceback (most recent call last):
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/sandman/sandman.py", line 388, in get_collection
    return collection_response(resources)
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/sandman/sandman.py", line 220, in collection_response
    return _collection_json_response(resources)
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/sandman/sandman.py", line 100, in _collection_json_response
    result_list.append(resource.as_dict())
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/sandman/model/models.py", line 96, in as_dict
    result_dict['links'] = self.links()
  File "/home/dzou/sandman_env/lib/python2.7/site-packages/sandman/model/models.py", line 70, in links
    links.append({'rel': endpoint, 'uri': '/{}/{}'.format(endpoint, getattr(self, column))})
AttributeError: 'job_schedule' object has no attribute 'name'

**Comment by jeffknupp** [comment]
Pretty sure I know what's going on. Could you send me the "create table" command for your tables so I can add this as a test case?
