### ISSUE TITLE
sqlalchemy.exc.NoSuchTableError: sandman with basic example

### ISSUE THREAD

**Issue by n3storm** [jeffknupp/sandman#21]
I started with real databases until creating a very simple database with one table, two fields, and always same error.

I am registering and not registering the table.

``` python
from sandman.model import register, activate, Model

class Banner(Model):
    __tablename__ = 'sandman'

register(Banner)
activate(admin=True)

from sandman import app, db

app.config['DEBUG'] = True
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:xxx@localhost/mydb'
app.run()
```

Error trace:

```
Traceback (most recent call last):
  File "hoya.py", line 7, in <module>
    activate(admin=True)
  File "/usr/local/lib/python2.7/dist-packages/sandman/model/__init__.py", line 78, in activate
    Model.prepare(db.engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/api.py", line 470, in prepare
    cls._sa_decl_prepare(thingy.local_table, engine)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/ext/declarative/api.py", line 486, in _sa_decl_prepare
    schema=local_table.schema)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/schema.py", line 322, in __new__
    table._init_existing(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/schema.py", line 465, in _init_existing
    self.metadata, autoload_with, include_columns, exclude_columns)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/schema.py", line 413, in _autoload
    self, include_columns, exclude_columns
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1595, in run_callable
    return conn.run_callable(callable_, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1118, in run_callable
    return callable_(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 262, in reflecttable
    return insp.reflecttable(table, include_columns, exclude_columns)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/reflection.py", line 461, in reflecttable
    raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: sandman
```

Debian 7, python 2.7, Maria Db 5.x

I feel a bit dumb for not being able to run the simplest setup, if there is anything else I can provide please tell me.

Thanks

**Comment by n3storm** [comment]
Last post at reddit thread helped me:

activate() MUST go after sqlalchemy config.

Please close this issue and/or clarify docs :)
