### ISSUE TITLE
Bootstrap Error on loading admin

### ISSUE THREAD

**Issue by ghost** [jeffknupp/sandman#32]
Output of `sandmanctl --all-columns-primary sqlite:////Users/jan/History`:

```
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'current_path'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'target_path'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'url'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'lower_term'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'term'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'key'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'value'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'title'
  default, primary_key))
sandmanctl
 * Running on http://0.0.0.0:5000/
 * Restarting with reloader
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'current_path'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'target_path'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'url'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'lower_term'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'term'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'key'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'value'
  default, primary_key))
/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/base.py:808: SAWarning: Did not recognize type 'LONGVARCHAR' of column 'title'
  default, primary_key))
sandmanctl
127.0.0.1 - - [03/Jan/2014 15:43:01] "GET /admin HTTP/1.1" 301 -
127.0.0.1 - - [03/Jan/2014 15:43:01] "GET /admin/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_admin/base.py", line 60, in inner
    return f(self, *args, **kwargs)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_admin/base.py", line 344, in index
    return self.render(self._template)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_admin/base.py", line 254, in render
    return render_template(template, **kwargs)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_admin/templates/admin/index.html", line 1, in top-level template code
    {% extends 'admin/master.html' %}
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_admin/templates/admin/master.html", line 1, in top-level template code
    {% extends admin_base_template %}
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_admin/templates/admin/base.html", line 11, in top-level template code
    {% block head_css %}
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask_admin/templates/admin/base.html", line 12, in block "head_css"
    <link href="{{ url_for('admin.static', filename='bootstrap/css/bootstrap.css') }}" rel="stylesheet">
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('admin.static', {'filename': 'bootstrap/css/bootstrap.css'}, None)
```

**Comment by jeffknupp** [comment]
Yeah, this is some weirdness with one of the packages. I re-pinned some of them and caught this bug. Will be fixed today.

**Comment by jeffknupp** [comment]
This is now fixed.
