### ISSUE TITLE
Error trying to use sandmanctl with sqlite3 database supplied via relative path

### ISSUE THREAD

**Issue by ghost** [jeffknupp/sandman#34]
```
$ ls -l History
-rw-r--r-- 1 jan staff 5906432 Dec 26 00:38 History
$ sandmanctl --all-columns-primary sqlite:///History
Traceback (most recent call last):
  File "/Users/jan/.virtualenvs/foo/bin/sandmanctl", line 9, in <module>
    load_entry_point('sandman==0.7.0', 'console_scripts', 'sandmanctl')()
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sandman/sandmanctl.py", line 58, in main
    activate(name='sandmanctl')
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sandman/model/utils.py", line 150, in activate
    prepare_relationships(current_app)
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/sandman/model/utils.py", line 60, in prepare_relationships
    for cls in current_app.classes:
  File "/Users/jan/.virtualenvs/foo/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'classes'
```

(Using sqlite:////absolute/path/to/History "works" (see other bugs submitted))

**Comment by jeffknupp** [comment]
version 0.7 is a bit out of date. Can you update to either 0.7.2 or (better yet) the develop branch and re-test?

**Comment by dmoco** [comment]
0.7.5, relative path not working. In fact relative path has not worked for me in any of the recent versions. I have "test.sqlite" and sym-link to it "test.db" (just in case). Tried various combo's but no luck, only absolute path works.
