### ISSUE TITLE
Error template not found

### ISSUE THREAD

**Issue by dannystaple** [jeffknupp/sandman#52]
When rendering an error, the console outputs:

```
Traceback (most recent call last):
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/flask/app.py", line 1379, in handle_user_exception
    return handler(e)
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/sandman/sandman.py", line 64, in handle_exception
    return error.abort()
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/sandman/exception.py", line 24, in abort
    resp = make_response(render_template('error.html', error=self.code, message=self.message), self.code)
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/stapled/python_envs/ansible/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: error.html
```

Note - the admin template and interface appears to be fine - so it doesn't look like all templates are missing. 
I attempted to query something directly in the browser (as opposed to curl).

Environment information:

```
$ pip freeze
Flask==0.10.1
Flask-Admin==1.0.7
Flask-SQLAlchemy==1.0
Jinja2==2.7.1
MarkupSafe==0.18
PyYAML==3.10
SQLAlchemy==0.9.1
WTForms==1.0.5
Werkzeug==0.9.4
ansible==1.4.1
docopt==0.6.1
ecdsa==0.10
itsdangerous==0.23
paramiko==1.12.0
pycrypto==2.6.1
sandman==0.7.5
wsgiref==0.1.2

$ python --version
Python 2.7.5

$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 19 (Schrödinger’s Cat)
Release:    19
Codename:   Schrödinger’sCat
```

**Comment by stma** [comment]
almost the same error
jinja2.exceptions.TemplateNotFound
TemplateNotFound: collection.html

and also the admin page is correct!
I got this after I tried to use the REST API...
any idea so far?
Thanks a lot!

python version: Python 2.7.5+
Flask==0.10.1
Flask-Admin==1.0.7
Flask-SQLAlchemy==1.0
Jinja2==2.7.2
Mako==0.9.1
MarkupSafe==0.18
PyYAML==3.10
SQLAlchemy==0.9.1
Unidecode==0.04.14
WTForms==1.0.5
Werkzeug==0.9.4
alembic==0.6.2
argparse==1.2.1
csv-to-psql==0.1.dev
dataset==0.4.0
docopt==0.6.1
itsdangerous==0.23
lxml==3.3.0
psycopg2==2.5.2
python-slugify==0.0.7
sandman==0.7.5
temp-dir==0.1.1
unicodecsv==0.9.4
wsgiref==0.1.2

**Comment by stma** [comment]
This error doesn't appear if you use curl or your http request doesn't contain 'Accept' header (see sandman.py line 42.)

If you want to examine the API without you deleting this attribute from request header you should copy the template directory into your site-packages dir (site-packages/sandman-0.7.4-py2.7.egg/sandman/) or fallow the instructions [here](http://stackoverflow.com/questions/1612733/including-non-python-files-with-setup-py) and contribute ;)

I hope I could help...

**Comment by stma** [comment]
same as #45
