### ISSUE TITLE
fails on tables w/o primary key

### ISSUE THREAD

**Issue by bkcsfi** [jeffknupp/sandman#65]
on 0.7.7rc3-py2.7

I have an old firebird database with 100+ tables, 2 of which do not have a primary key.

sqla automap is able to reflect this db ok, but sandman falls down. I don't expect sandman to work with tables w/o a primary key, but it would be nice if it could just skip over these 2 tables.

```
    Traceback (most recent call last):
      File "/home/bkc/Python_Environments/sandman/bin/sandmanctl", line 9, in <module>
        load_entry_point('sandman==0.7.7rc3', 'console_scripts', 'sandmanctl')()
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/sandman/sandmanctl.py", line 63, in main
        activate(name='sandmanctl')
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/sandman/model/utils.py", line 146, in activate
        generate_endpoint_classes(db, generate_pks)
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/sandman/model/utils.py", line 30, in generate_endpoint_classes
        {'__tablename__': name})
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 510, in __init__
        DeclarativeMeta.__init__(self, name, bases, d)
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 53, in __init__
        _as_declarative(cls, classname, cls.__dict__)
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 326, in _as_declarative
        mt.map()
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 409, in map
        **mapper_args
      File "<string>", line 2, in mapper
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 603, in __init__
        self._configure_pks()
      File "/home/bkc/Python_Environments/sandman/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1193, in _configure_pks
        (self, self.mapped_table.description))
    sqlalchemy.exc.ArgumentError: Mapper Mapper|zsession_data|zsession_data could not assemble any primary key columns for mapped table 'zsession_data'
```

**Comment by jeffknupp** [comment]
Try using `sandmanctl -g` or setting `app.config["SANDMAN_GENERATE_PKS"] = True`. This is mentioned in the documentation.
