### ISSUE TITLE
sqlalchemy.exc.ArgumentError: Mapper Mapper|sqlite_sequence|sqlite_sequence could not assemble any primary key columns for mapped table 'sqlite_sequence'

### ISSUE THREAD

**Issue by Morrolan** [jeffknupp/sandman#73]
Hi,

I am having a problem getting sandman to open a simple sqlite3 database used in a python module that I have written.

Within my database there are 2 tables that I have not created - 1 table called 'revisions' which I believe was created by c9.io when I was developing on that cloud service, but this has caused the sqlite_sequence table to spawn.  As the sqlite documentation (http://www.sqlite.org/fileformat2.html#seqtab) states, you cannot drop this table once created.

When I try to run sandman, it falls over on this sqlite_sequence table.  Please see the error below.

The database in question is available from https://github.com/Morrolan/surrealism/blob/develop/surrealism/surrealism.sqlite

```
amber:surrealism morrolan$ sandmanctl sqlite:////Development/Python/surrealism/surrealism.sqlite
Traceback (most recent call last):
  File "/usr/local/bin/sandmanctl", line 8, in <module>
    load_entry_point('sandman==0.9.4', 'console_scripts', 'sandmanctl')()
  File "/Library/Python/2.7/site-packages/sandman/sandmanctl.py", line 73, in main
    activate(name='sandmanctl')
  File "/Library/Python/2.7/site-packages/sandman/model/utils.py", line 157, in activate
    generate_endpoint_classes(db, generate_pks)
  File "/Library/Python/2.7/site-packages/sandman/model/utils.py", line 39, in generate_endpoint_classes
    {'__tablename__': name})
  File "/Library/Python/2.7/site-packages/flask_sqlalchemy/__init__.py", line 510, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "/Library/Python/2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 50, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/Library/Python/2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 292, in _as_declarative
    mt.map()
  File "/Library/Python/2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 376, in map
    **mapper_args
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/__init__.py", line 1208, in mapper
    return Mapper(class_, local_table, *args, **params)
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/mapper.py", line 221, in __init__
    self._configure_pks()
  File "/Library/Python/2.7/site-packages/sqlalchemy/orm/mapper.py", line 818, in _configure_pks
    (self, self.mapped_table.description))
sqlalchemy.exc.ArgumentError: Mapper Mapper|sqlite_sequence|sqlite_sequence could not assemble any primary key columns for mapped table 'sqlite_sequence'
```

**Comment by jeffknupp** [comment]
If you're using the command line tool (`sandmanctl`), pass it the `-g` flag, which tells it to create sythetic primary keys for tables without one. If you're using it in a Python module, just set the app config variable `app.config['SANDMAN_GENERATE_PKS'] = True`. That does the same thing when using `sandman` programatically.

**Comment by zhangcheng-aa** [comment]
With sandman 0.9.8, the option is `--generate-pks` instead of `-g`
