### ISSUE TITLE
Tables with multiple fields on Primary Key

### ISSUE THREAD

**Issue by esparta** [jeffknupp/sandman#80]
I have a legacy database with some tables with composed primary keys:

``` sql

CREATE TABLE A(
     cve_a VARCHAR(2) NOT NULL,
     name VARCHAR(50),
     PRIMARY KEY (cve_a)
     );

CREATE TABLE complex (
    cve_a VARCHAR(2) NOT NULL, 
    cve_b VARCHAR(3) NOT NULL, 
    name VARCHAR(50), 
    PRIMARY KEY (cve_a, cve_b),
        FOREIGN KEY(cve_a) REFERENCES A (cve_a)
);
INSERT INTO A VALUES('01','One');
INSERT INTO complex VALUES ('01', '001', 'One One');
```

Can sandman REST API work with this kind of tables? 

`curl localhost:5000/as/` return:

``` json
{
  "resources": [
    {
      "cve_a": "01", 
      "links": [
        {
          "rel": "self", 
          "uri": "/as/01"
        }
      ], 
      "name": "One", 
      "self": "/as/01"
    }
  ]
}
```

`curl localhost:5000/complexs` returns:

``` json
{
  "resources": [
    {
      "a_url": "/A/01", 
      "cve_a": "01", 
      "cve_b": "001", 
      "links": [
        {
          "rel": "related", 
          "uri": "/A/01"
        }, 
        {
          "rel": "self", 
          "uri": "/complexs/01"
        }
      ], 
      "name": "One One", 
      "self": "/complexs/01"
    }
  ]
}
```

Of course, if I try `curl localhost:5000/complexs/01` I get the following error:

```
Traceback (most recent call last):
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/sandman/decorators.py", line 27, in wrapped
    rv = f(*args, **kwargs)
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/sandman/sandman.py", line 445, in get_resource
    resource = retrieve_resource(collection, key)
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/sandman/sandman.py", line 245, in retrieve_resource
    resource = session.query(cls).get(key)
  File "/home/esparta/.virtualenvs/sandman/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 798, in get
    ','.join("'%s'" % c for c in mapper.primary_key))
InvalidRequestError: Incorrect number of values in identifier to formulate primary key for query.get(); primary key columns are 'complex.cve_a','complex.cve_b'
```

What can I do in the understanding that I can't generate a new field?

**Comment by esparta** [comment]
It seems like a no: https://github.com/mrjoes/flask-admin/issues/34
