### ISSUE TITLE
'Response' object has no attribute 'get_data'

### ISSUE THREAD

**Issue by sauloal** [jeffknupp/sandman#90]
Traceback (most recent call last):
  File "/home/assembly/.local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/assembly/.local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/assembly/.local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/assembly/.local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/assembly/.local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/assembly/.local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/assembly/.local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/assembly/.local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/assembly/.local/lib/python2.7/site-packages/sandman-0.9.8-py2.7.egg/sandman/decorators.py", line 29, in wrapped
    etag = '"' + hashlib.md5(rv.get_data()).hexdigest() + '"'
AttributeError: 'Response' object has no attribute 'get_data'

**Comment by sauloal** [comment]
Fixed
easy_install -U Werkzeug
Best match: Werkzeug 0.9.6
